### ISSUE TITLE
Bottom sheet title and contents color

### ISSUE THREAD

**Issue by Fuhrmann** [Aohayou/MaterialValues#9]
Hi!

In the Google Material Design docs the Bottom Sheet title is optional, but the color is #000 %54 and the contents text color is #000 87%:

![image](https://cloud.githubusercontent.com/assets/1160365/20446823/46fd4580-adba-11e6-844f-712ec2a8a5f4.png)

You can see the color difference here:

![image](https://cloud.githubusercontent.com/assets/1160365/20446881/891ce18c-adba-11e6-9bd5-cdab90f942ef.png)

But when using `@color\material_bottom_sheet_title_text_color` and `@color\material_bottom_sheet_contents_text_color` they are the same:

![image](https://cloud.githubusercontent.com/assets/1160365/20446911/b263f33c-adba-11e6-83fe-956e695327cf.png)

wich is 87%:

`<color name="material_color_black_87_percent">#DE000000</color>`

**Comment by esnaultdev** [comment]
PR merged into dev
